import { ArrowSquareOut, DownloadSimple, LockKey, Moon, Plus, SignOut, Swatches, Trash, UserCircle } from "@phosphor-icons/react";
import { useState } from "react";
import { useAuth } from "../context/AuthContext";
import { useLedger } from "../context/LedgerContext";
import { getCategory } from "../lib/categories";
import { formatMoney } from "../lib/currency";
import type { CurrencyCode, ThemePreference, TransactionKind } from "../types";

const currencies: { code: CurrencyCode; label: string }[] = [
  { code: "NPR", label: "Nepalese rupee" }, { code: "USD", label: "US dollar" }, { code: "AUD", label: "Australian dollar" },
];
const categoryColors = ["#135dea", "#2b8a50", "#e8675a", "#8867c7", "#d69531", "#3a8e91"];

export function SettingsPage({ onLock }: { onLock: () => void }) {
  const { signOut, isDemo, user, changePassword, deleteAccount } = useAuth();
  const { profile, transactions, customCategories, updateProfile, saveCustomCategory, deleteCustomCategory, resetDemo } = useLedger();
  const [name, setName] = useState(profile.displayName); const [currency, setCurrency] = useState<CurrencyCode>(profile.currency); const [theme, setTheme] = useState<ThemePreference>(profile.theme); const [hideAmounts, setHideAmounts] = useState(profile.hideAmounts); const [autoLock, setAutoLock] = useState(profile.autoLockMinutes); const [status, setStatus] = useState<string | null>(null);
  const [categoryName, setCategoryName] = useState(""); const [categoryKind, setCategoryKind] = useState<TransactionKind | "both">("expense"); const [categoryColor, setCategoryColor] = useState(categoryColors[0]); const [categoryError, setCategoryError] = useState<string | null>(null);
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [securityStatus, setSecurityStatus] = useState<string | null>(null);
  const save = async (event: React.FormEvent) => { event.preventDefault(); await updateProfile({ displayName: name.trim() || "Personal ledger", currency, theme, hideAmounts, autoLockMinutes: autoLock }); setStatus("Preferences saved."); window.setTimeout(() => setStatus(null), 2500); };
  const addCategory = async (event: React.FormEvent) => { event.preventDefault(); try { setCategoryError(null); await saveCustomCategory({ name: categoryName, kind: categoryKind, color: categoryColor }); setCategoryName(""); } catch (caught) { setCategoryError(caught instanceof Error ? caught.message : "Could not add category."); } };
  const exportCsv = () => { const rows = [["date", "type", "category", "note", "amount", "currency", "tags"], ...transactions.map((item) => [item.occurredOn, item.kind, getCategory(item.category, customCategories).label, item.note, String(item.amountMinor / 100), profile.currency, item.tags.join(", ")])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "paper-ledger-transactions.csv"; anchor.click(); URL.revokeObjectURL(url); };

  return <div className="page settings-page"><header className="page-header"><div><span className="eyebrow">Your space</span><h1>Profile & settings</h1><p>Choose how your personal ledger looks, reads, and protects itself.</p></div></header><section className="settings-grid">
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><UserCircle size={23} /></span><div><h2>Profile</h2><p>{isDemo ? "Demo data stays in this browser." : user?.email}</p></div></div><form onSubmit={save} className="settings-form"><label><span>Display name</span><input value={name} onChange={(event) => setName(event.target.value)} maxLength={50} /></label><label><span>Default currency</span><select value={currency} onChange={(event) => setCurrency(event.target.value as CurrencyCode)}>{currencies.map((item) => <option key={item.code} value={item.code}>{item.code} — {item.label}</option>)}</select><small>There is no foreign-exchange conversion; this labels the whole personal ledger.</small></label><div className="currency-preview"><span>Preview</span><strong>{formatMoney(3925000, currency)}</strong></div>{status && <div className="form-success">{status}</div>}<button className="primary-button">Save preferences</button></form></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><Moon size={23} /></span><div><h2>Appearance & privacy</h2><p>Control contrast and shoulder-surfing protection.</p></div></div><form onSubmit={save} className="settings-form"><label><span>Theme</span><select value={theme} onChange={(event) => setTheme(event.target.value as ThemePreference)}><option value="system">Use system setting</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label className="toggle-row"><span><strong>Hide amounts by default</strong><small>Blur monetary values until you reveal them.</small></span><input type="checkbox" checked={hideAmounts} onChange={(event) => setHideAmounts(event.target.checked)} /></label><label><span>Auto-lock after inactivity</span><select value={autoLock} onChange={(event) => setAutoLock(Number(event.target.value))}><option value={0}>Never</option><option value={1}>1 minute</option><option value={5}>5 minutes</option><option value={15}>15 minutes</option><option value={30}>30 minutes</option></select></label><button className="primary-button">Save appearance</button><button type="button" className="secondary-button" onClick={onLock}><LockKey size={18} />Lock now</button></form></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><Swatches size={23} /></span><div><h2>Custom categories</h2><p>Make the ledger fit your real life.</p></div></div><form className="category-creator" onSubmit={addCategory}><input value={categoryName} onChange={(event) => setCategoryName(event.target.value)} placeholder="Category name" maxLength={30} required /><select value={categoryKind} onChange={(event) => setCategoryKind(event.target.value as TransactionKind | "both")}><option value="expense">Expense</option><option value="income">Income</option><option value="both">Both</option></select><div className="color-picker">{categoryColors.map((color) => <button key={color} type="button" className={categoryColor === color ? "active" : ""} style={{ backgroundColor: color }} onClick={() => setCategoryColor(color)} aria-label={`Use ${color}`} />)}</div>{categoryError && <div className="form-error">{categoryError}</div>}<button className="primary-button"><Plus size={17} />Add category</button></form><div className="custom-category-list">{customCategories.map((item) => <div key={item.id}><span className="legend-dot" style={{ backgroundColor: item.color }} /><span>{item.name}</span><small>{item.kind}</small><button className="icon-button danger" onClick={() => void deleteCustomCategory(item.id).catch((error: Error) => setCategoryError(error.message))} aria-label={`Delete ${item.name}`}><Trash size={16} /></button></div>)}{!customCategories.length && <p>No custom categories yet.</p>}</div></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><DownloadSimple size={23} /></span><div><h2>Your data</h2><p>Take your entries with you at any time.</p></div></div><button className="settings-action" onClick={exportCsv}><div><strong>Export CSV</strong><span>{transactions.length} entries ready to download</span></div><ArrowSquareOut size={20} /></button>{isDemo && <button className="settings-action" onClick={resetDemo}><div><strong>Reset sample data</strong><span>Restore the original demo ledger</span></div><ArrowSquareOut size={20} /></button>}<button className="settings-action danger-text" onClick={() => void signOut()}><div><strong>Sign out</strong><span>Return to the welcome screen</span></div><SignOut size={20} /></button></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><LockKey size={23} /></span><div><h2>Account security</h2><p>Update your credentials or permanently remove your account.</p></div></div><form className="settings-form" onSubmit={(event) => { event.preventDefault(); void changePassword(currentPassword, newPassword).then(() => { setCurrentPassword(""); setNewPassword(""); setSecurityStatus("Password changed and other sessions signed out."); }).catch((error: Error) => setSecurityStatus(error.message)); }}><label><span>Current password</span><input type="password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required /></label><label><span>New password</span><input type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} autoComplete="new-password" required /></label>{securityStatus && <div className="form-success">{securityStatus}</div>}<button className="primary-button">Change password</button><button type="button" className="secondary-button danger-text" onClick={() => { const password = window.prompt("Enter your password to permanently delete this account and every ledger entry."); if (password && window.confirm("Delete your account permanently? This cannot be undone.")) void deleteAccount(password).catch((error: Error) => setSecurityStatus(error.message)); }}><Trash size={18} />Delete account</button></form></article>
  </section></div>;
}
