import { ArrowSquareOut, DownloadSimple, EyeSlash, LockKey, Plus, Swatches, Trash, UserCircle } from "@phosphor-icons/react";
import { Modal, PasswordInput, Select, Switch, TextInput } from "@mantine/core";
import { useState } from "react";
import { ButtonSpinner } from "../components/ButtonSpinner";
import { useAuth } from "../context/AuthContext";
import { useLedger } from "../context/LedgerContext";
import { getCategory } from "../lib/categories";
import { formatMoney } from "../lib/currency";
import { paymentAccountLabel } from "../lib/payment-accounts";
import type { CurrencyCode, TransactionKind } from "../types";

const currencies: { code: CurrencyCode; label: string }[] = [
  { code: "NPR", label: "Nepalese rupee" }, { code: "USD", label: "US dollar" }, { code: "AUD", label: "Australian dollar" },
];
const categoryColors = ["#557f69", "#3f6653", "#789685", "#8f4c49", "#a76d62", "#745d56"];

export function SettingsPage({ onLock }: { onLock: () => void }) {
  const { isDemo, user, changePassword, deleteAccount } = useAuth();
  const { profile, transactions, customCategories, updateProfile, saveCustomCategory, deleteCustomCategory, savePin, removePin, resetDemo } = useLedger();
  const [name, setName] = useState(profile.displayName); const [currency, setCurrency] = useState<CurrencyCode>(profile.currency); const [hideAmounts, setHideAmounts] = useState(profile.hideAmounts); const [autoLock, setAutoLock] = useState(profile.autoLockMinutes); const [status, setStatus] = useState<string | null>(null);
  const [categoryName, setCategoryName] = useState(""); const [categoryKind, setCategoryKind] = useState<TransactionKind | "both">("expense"); const [categoryColor, setCategoryColor] = useState(categoryColors[0]); const [categoryError, setCategoryError] = useState<string | null>(null);
  const [currentPassword, setCurrentPassword] = useState(""); const [newPassword, setNewPassword] = useState(""); const [securityStatus, setSecurityStatus] = useState<string | null>(null);
  const [deleteModalOpen, setDeleteModalOpen] = useState(false); const [deletePassword, setDeletePassword] = useState(""); const [deleteError, setDeleteError] = useState<string | null>(null);
  const [currentPin, setCurrentPin] = useState(""); const [newPin, setNewPin] = useState(""); const [confirmPin, setConfirmPin] = useState(""); const [pinStatus, setPinStatus] = useState<string | null>(null); const [pinAction, setPinAction] = useState<"save" | "remove" | null>(null);
  const [savingPreferences, setSavingPreferences] = useState(false); const [categoryAction, setCategoryAction] = useState<string | null>(null); const [securityAction, setSecurityAction] = useState<"password" | "delete" | null>(null);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (savingPreferences) return; setSavingPreferences(true); try { setStatus(null); await updateProfile({ displayName: name.trim() || "Personal ledger", currency, hideAmounts, autoLockMinutes: autoLock }); setStatus("Preferences saved."); window.setTimeout(() => setStatus(null), 2500); } catch (caught) { setStatus(caught instanceof Error ? caught.message : "Could not save preferences."); } finally { setSavingPreferences(false); } };
  const addCategory = async (event: React.FormEvent) => { event.preventDefault(); if (categoryAction) return; setCategoryAction("add"); try { setCategoryError(null); await saveCustomCategory({ name: categoryName, kind: categoryKind, color: categoryColor }); setCategoryName(""); } catch (caught) { setCategoryError(caught instanceof Error ? caught.message : "Could not add category."); } finally { setCategoryAction(null); } };
  const removeCategory = async (id: string) => { if (categoryAction) return; setCategoryAction(id); try { setCategoryError(null); await deleteCustomCategory(id); } catch (caught) { setCategoryError(caught instanceof Error ? caught.message : "Could not delete category."); } finally { setCategoryAction(null); } };
  const updatePassword = async (event: React.FormEvent) => { event.preventDefault(); if (securityAction) return; setSecurityAction("password"); try { setSecurityStatus(null); await changePassword(currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); setSecurityStatus("Password changed and other sessions signed out."); } catch (caught) { setSecurityStatus(caught instanceof Error ? caught.message : "Could not change password."); } finally { setSecurityAction(null); } };
  const openDeleteModal = () => { setDeletePassword(""); setDeleteError(null); setDeleteModalOpen(true); };
  const closeDeleteModal = () => { if (securityAction === "delete") return; setDeleteModalOpen(false); setDeletePassword(""); setDeleteError(null); };
  const removeAccount = async (event: React.FormEvent) => { event.preventDefault(); if (securityAction || !deletePassword) return; setSecurityAction("delete"); try { setDeleteError(null); setSecurityStatus(null); await deleteAccount(deletePassword); } catch (caught) { setDeleteError(caught instanceof Error ? caught.message : "Could not delete account."); setSecurityAction(null); } };
  const updatePin = async (event: React.FormEvent) => { event.preventDefault(); if (pinAction) return; setPinStatus(null); if (newPin !== confirmPin) { setPinStatus("The new PINs do not match."); return; } setPinAction("save"); try { await savePin(newPin, profile.hasPin ? currentPin : undefined); setCurrentPin(""); setNewPin(""); setConfirmPin(""); setPinStatus(profile.hasPin ? "Ledger PIN changed." : "Ledger PIN set. You can now lock your ledger."); } catch (caught) { setPinStatus(caught instanceof Error ? caught.message : "Could not save your PIN."); } finally { setPinAction(null); } };
  const disablePin = async () => { if (pinAction || !currentPin || !window.confirm("Remove the ledger PIN? Auto-lock will also be turned off.")) return; setPinAction("remove"); try { setPinStatus(null); await removePin(currentPin); setCurrentPin(""); setNewPin(""); setConfirmPin(""); setAutoLock(0); setPinStatus("Ledger PIN removed. Locking is now off."); } catch (caught) { setPinStatus(caught instanceof Error ? caught.message : "Could not remove your PIN."); } finally { setPinAction(null); } };
  const exportCsv = () => { const rows = [["date", "type", "category", "subcategory", "area", "note", "amount", "currency", "payment mode", "payment account id", "payment account"], ...transactions.map((item) => [item.occurredOn, item.kind, getCategory(item.category, customCategories).label, item.subcategory ?? "", item.area ?? "", item.note, String(item.amountMinor / 100), profile.currency, item.paymentMode, item.paymentAccountId ?? "", item.paymentAccount ? paymentAccountLabel(item.paymentAccount) : ""])]; const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "save-yo-rupee-transactions.csv"; anchor.click(); URL.revokeObjectURL(url); };

  return <><div className="page settings-page"><header className="page-header"><div><span className="eyebrow">Your space</span><h1>Profile & settings</h1><p>Choose how your personal ledger looks, reads, and protects itself.</p></div></header><div className="settings-sections">
    <section className="settings-section" aria-labelledby="basic-profile-heading"><h2 id="basic-profile-heading" className="settings-section-heading">Basic profile</h2><div className="settings-grid settings-grid-single">
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><UserCircle size={23} /></span><div><h2>Profile</h2><p>{isDemo ? "Demo data stays in this browser." : user?.email}</p></div></div><form onSubmit={save} className="settings-form" aria-busy={savingPreferences}><TextInput label="Display name" value={name} onChange={(event) => setName(event.target.value)} maxLength={50} /><Select label="Default currency" value={currency} onChange={(value) => value && setCurrency(value as CurrencyCode)} data={currencies.map((item) => ({ value: item.code, label: `${item.code} — ${item.label}` }))} description="There is no foreign-exchange conversion; this labels the whole personal ledger." allowDeselect={false} /><div className="currency-preview"><span>Preview</span><strong>{formatMoney(3925000, currency)}</strong></div>{status && <div className="form-success" role="status">{status}</div>}<button className="primary-button" disabled={savingPreferences}>{savingPreferences ? <><ButtonSpinner />Saving…</> : "Save preferences"}</button></form></article>
    </div></section>
    <section className="settings-section" aria-labelledby="customizations-heading"><h2 id="customizations-heading" className="settings-section-heading">Customizations</h2><div className="settings-grid">
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><EyeSlash size={23} /></span><div><h2>Privacy</h2><p>Control shoulder-surfing protection and automatic locking.</p></div></div><form onSubmit={save} className="settings-form" aria-busy={savingPreferences}><Switch label="Hide amounts by default" description="Mask monetary values until you reveal them." checked={hideAmounts} onChange={(event) => setHideAmounts(event.currentTarget.checked)} /><Select label="Auto-lock after inactivity" value={String(profile.hasPin ? autoLock : 0)} onChange={(value) => value !== null && setAutoLock(Number(value))} data={[{ value: "0", label: "Never" }, { value: "1", label: "1 minute" }, { value: "5", label: "5 minutes" }, { value: "15", label: "15 minutes" }, { value: "30", label: "30 minutes" }]} description={profile.hasPin ? "Use your ledger PIN to unlock." : "Set up a ledger PIN below to enable auto-lock."} disabled={!profile.hasPin} allowDeselect={false} /><button className="primary-button" disabled={savingPreferences}>{savingPreferences ? <><ButtonSpinner />Saving…</> : "Save privacy settings"}</button><button type="button" className="secondary-button" onClick={onLock} disabled={!profile.hasPin} title={profile.hasPin ? undefined : "Set up a ledger PIN first"}><LockKey size={18} />{profile.hasPin ? "Lock now" : "Set up a PIN to lock"}</button></form></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><Swatches size={23} /></span><div><h2>Custom categories</h2><p>Make the ledger fit your real life.</p></div></div><form className="category-creator" onSubmit={addCategory} aria-busy={categoryAction === "add"}><TextInput value={categoryName} onChange={(event) => setCategoryName(event.target.value)} placeholder="Category name" maxLength={30} required disabled={categoryAction === "add"} /><Select value={categoryKind} disabled={categoryAction === "add"} onChange={(value) => value && setCategoryKind(value as TransactionKind | "both")} data={[{ value: "expense", label: "Expense" }, { value: "income", label: "Income" }, { value: "both", label: "Both" }]} allowDeselect={false} /><div className="color-picker">{categoryColors.map((color) => <button key={color} type="button" className={categoryColor === color ? "active" : ""} style={{ backgroundColor: color }} onClick={() => setCategoryColor(color)} aria-label={`Use ${color}`} />)}</div>{categoryError && <div className="form-error" role="alert">{categoryError}</div>}<button className="primary-button" disabled={Boolean(categoryAction)}>{categoryAction === "add" ? <><ButtonSpinner />Adding…</> : <><Plus size={17} />Add category</>}</button></form><div className="custom-category-list">{customCategories.map((item) => <div key={item.id} aria-busy={categoryAction === item.id}><span className="legend-dot" style={{ backgroundColor: item.color }} /><span>{item.name}</span><small>{categoryAction === item.id ? "Removing…" : item.kind}</small><button className="icon-button danger" disabled={Boolean(categoryAction)} onClick={() => void removeCategory(item.id)} aria-label={`Delete ${item.name}`}>{categoryAction === item.id ? <ButtonSpinner /> : <Trash size={16} />}</button></div>)}{!customCategories.length && <p>No custom categories yet.</p>}</div></article>
    </div></section>
    <section className="settings-section" aria-labelledby="security-heading"><h2 id="security-heading" className="settings-section-heading">Security</h2><div className="settings-grid">
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><LockKey size={23} /></span><div><h2>Ledger PIN</h2><p>{profile.hasPin ? "Change or remove the PIN used to unlock this ledger." : "Set a short PIN before adding accounts or enabling ledger locking."}</p></div></div><form className="settings-form" onSubmit={updatePin} aria-busy={Boolean(pinAction)}>{profile.hasPin && <PasswordInput label="Current PIN" value={currentPin} onChange={(event) => setCurrentPin(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="current-password" minLength={4} maxLength={6} required disabled={Boolean(pinAction)} />}<PasswordInput label={profile.hasPin ? "New PIN" : "Create PIN"} description="Use 4 to 6 digits." value={newPin} onChange={(event) => setNewPin(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="new-password" minLength={4} maxLength={6} required disabled={Boolean(pinAction)} /><PasswordInput label="Confirm new PIN" value={confirmPin} onChange={(event) => setConfirmPin(event.target.value.replace(/\D/g, "").slice(0, 6))} inputMode="numeric" autoComplete="new-password" minLength={4} maxLength={6} required disabled={Boolean(pinAction)} />{pinStatus && <div className={pinStatus.startsWith("Ledger PIN") ? "form-success" : "form-error"} role="status">{pinStatus}</div>}<button className="primary-button" disabled={Boolean(pinAction) || newPin.length < 4 || confirmPin.length < 4}>{pinAction === "save" ? <><ButtonSpinner />Saving PIN…</> : profile.hasPin ? "Change PIN" : "Set PIN"}</button>{profile.hasPin && <button type="button" className="secondary-button danger-text" disabled={Boolean(pinAction) || currentPin.length < 4} onClick={() => void disablePin()}>{pinAction === "remove" ? <><ButtonSpinner />Removing PIN…</> : "Remove PIN and turn off locking"}</button>}</form></article>
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><LockKey size={23} /></span><div><h2>Account security</h2><p>Update your credentials or permanently remove your account.</p></div></div><form className="settings-form" onSubmit={updatePassword} aria-busy={Boolean(securityAction)}><PasswordInput label="Current password" value={currentPassword} onChange={(event) => setCurrentPassword(event.target.value)} autoComplete="current-password" required disabled={Boolean(securityAction)} /><PasswordInput label="New password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} minLength={8} autoComplete="new-password" required disabled={Boolean(securityAction)} />{securityStatus && <div className="form-success" role="status">{securityStatus}</div>}<button className="primary-button" disabled={Boolean(securityAction)}>{securityAction === "password" ? <><ButtonSpinner />Changing password…</> : "Change password"}</button><button type="button" className="secondary-button danger-text" disabled={Boolean(securityAction)} onClick={openDeleteModal}><Trash size={18} />Delete account</button></form></article>
    </div></section>
    <section className="settings-section" aria-labelledby="your-data-heading"><h2 id="your-data-heading" className="settings-section-heading">Your data</h2><div className="settings-grid settings-grid-single">
    <article className="settings-panel"><div className="settings-title"><span className="settings-icon"><DownloadSimple size={23} /></span><div><h2>Data controls</h2><p>Take your entries with you at any time.</p></div></div><button className="settings-action" onClick={exportCsv}><div><strong>Export CSV</strong><span>{transactions.length} entries ready to download</span></div><ArrowSquareOut size={20} /></button>{isDemo && <button className="settings-action" onClick={resetDemo}><div><strong>Reset sample data</strong><span>Restore the original demo ledger</span></div><ArrowSquareOut size={20} /></button>}</article>
    </div></section>
  </div></div><Modal opened={deleteModalOpen} onClose={closeDeleteModal} centered closeOnClickOutside={securityAction !== "delete"} closeOnEscape={securityAction !== "delete"} withCloseButton={securityAction !== "delete"} overlayProps={{ backgroundOpacity: .55, blur: 5 }} classNames={{ content: "delete-account-dialog", header: "delete-account-dialog-header", title: "delete-account-dialog-title" }} title={<><span className="delete-account-icon"><Trash size={21} /></span><span>Delete account</span></>}><p className="delete-account-warning">This permanently deletes your account and every ledger entry. This action cannot be undone.</p><form className="delete-account-form" onSubmit={removeAccount} aria-busy={securityAction === "delete"}><PasswordInput label="Enter your password to confirm" value={deletePassword} onChange={(event) => setDeletePassword(event.target.value)} autoComplete="current-password" autoFocus required disabled={securityAction === "delete"} error={deleteError ?? undefined} /><div className="dialog-actions"><button type="button" className="secondary-button" onClick={closeDeleteModal} disabled={securityAction === "delete"}>Cancel</button><button type="submit" className="delete-account-button" disabled={!deletePassword || securityAction === "delete"}>{securityAction === "delete" ? <><ButtonSpinner />Deleting account…</> : <><Trash size={17} />Delete permanently</>}</button></div></form></Modal></>;
}
