import { DownloadSimple, FunnelSimple, MagnifyingGlass, Plus, UploadSimple, X } from "@phosphor-icons/react";
import { NumberInput, Select, TextInput } from "@mantine/core";
import { DatePickerInput } from "@mantine/dates";
import { useEffect, useMemo, useRef, useState } from "react";
import { EmptyState } from "../components/EmptyState";
import { ButtonSpinner } from "../components/ButtonSpinner";
import { TransactionRow } from "../components/TransactionRow";
import { allCategoriesFor, CATEGORIES, getCategory } from "../lib/categories";
import { parseTransactionCsv, TRANSACTION_CSV_TEMPLATE } from "../lib/csv";
import type { CurrencyCode, CustomCategory, LedgerTransaction, PaymentAccount, PaymentMode, TransactionDraft, TransactionKind } from "../types";

interface TransactionsPageProps {
  currency: CurrencyCode; transactions: LedgerTransaction[]; customCategories: CustomCategory[]; paymentAccounts: PaymentAccount[];
  onAdd: () => void; onEdit: (transaction: LedgerTransaction) => void; onDelete: (transaction: LedgerTransaction) => Promise<void>;
  onImport: (drafts: TransactionDraft[]) => Promise<number>;
}

export function TransactionsPage({ currency, transactions, customCategories, paymentAccounts, onAdd, onEdit, onDelete, onImport }: TransactionsPageProps) {
  const [query, setQuery] = useState(""); const [kind, setKind] = useState<TransactionKind | "all">("all");
  const [category, setCategory] = useState("all"); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [min, setMin] = useState(""); const [max, setMax] = useState(""); const [paymentMode, setPaymentMode] = useState<PaymentMode | "all">("all"); const [filtersOpen, setFiltersOpen] = useState(false);
  const [preview, setPreview] = useState<TransactionDraft[] | null>(null); const [importErrors, setImportErrors] = useState<string[]>([]); const [importing, setImporting] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const templateHref = `data:text/csv;charset=utf-8,${encodeURIComponent(`\uFEFF${TRANSACTION_CSV_TEMPLATE}`)}`;
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const filterCategories = useMemo(() => kind === "all" ? [...CATEGORIES, ...customCategories] : [...allCategoriesFor(kind, customCategories)], [kind, customCategories]);
  useEffect(() => { if (category !== "all" && !filterCategories.some((item) => item.id === category)) setCategory("all"); }, [category, filterCategories]);
  const sorted = useMemo(() => [...transactions]
    .filter((item) => kind === "all" || item.kind === kind)
    .filter((item) => category === "all" || item.category === category)
    .filter((item) => !from || item.occurredOn >= from).filter((item) => !to || item.occurredOn <= to)
    .filter((item) => !min || item.amountMinor >= Number(min) * 100).filter((item) => !max || item.amountMinor <= Number(max) * 100)
    .filter((item) => paymentMode === "all" || item.paymentMode === paymentMode)
    .filter((item) => `${item.note} ${getCategory(item.category, customCategories).label} ${item.subcategory ?? ""} ${item.area ?? ""} ${item.paymentAccount?.provider ?? ""}`.toLowerCase().includes(query.toLowerCase()))
    .sort((a, b) => `${b.occurredOn}${b.createdAt}`.localeCompare(`${a.occurredOn}${a.createdAt}`)), [transactions, kind, category, from, to, min, max, paymentMode, query, customCategories]);

  const readFile = async (file: File) => { const result = parseTransactionCsv(await file.text(), customCategories, paymentAccounts); setPreview(result.rows); setImportErrors(result.errors); };
  const importRows = async () => { if (!preview?.length) return; setImporting(true); try { await onImport(preview); setPreview(null); setImportErrors([]); } finally { setImporting(false); } };
  const remove = async (transaction: LedgerTransaction) => { if (deletingId) return; setDeletingId(transaction.id); try { await onDelete(transaction); } finally { setDeletingId(null); } };
  const resetFilters = () => { setKind("all"); setCategory("all"); setFrom(""); setTo(""); setMin(""); setMax(""); setPaymentMode("all"); setQuery(""); };

  return <div className="page list-page">
    <header className="page-header"><div><span className="eyebrow">Your ledger</span><h1>Transactions</h1><p>Every income and expense entry, in one clear timeline.</p></div><div className="transaction-actions"><div className="header-actions"><input ref={fileRef} className="visually-hidden" type="file" accept=".csv,text/csv" onChange={(event) => event.target.files?.[0] && void readFile(event.target.files[0])} /><button className="secondary-button" onClick={() => fileRef.current?.click()}><UploadSimple size={18} />Import CSV</button><button className="primary-button" onClick={onAdd}><Plus size={18} />Add transaction</button></div><div className="csv-template-help"><span>New to CSV imports?</span><a href={templateHref} download="transaction-import-template.csv"><DownloadSimple size={14} />Download CSV template</a></div></div></header>
    <section className="toolbar"><TextInput className="search-field" aria-label="Search transactions" leftSection={<MagnifyingGlass size={19} />} rightSection={query ? <button onClick={() => setQuery("")} aria-label="Clear search"><X size={17} /></button> : null} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transactions" /><div className="filter-tabs" aria-label="Filter transaction type"><FunnelSimple size={18} />{(["all", "expense", "income"] as const).map((value) => <button key={value} className={kind === value ? "active" : ""} onClick={() => setKind(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}<button className={filtersOpen ? "active" : ""} onClick={() => setFiltersOpen((open) => !open)} aria-expanded={filtersOpen}>More</button></div></section>
    {filtersOpen && <section className="advanced-filters"><Select label={kind === "all" ? "Category" : `${kind === "expense" ? "Expense" : "Income"} category`} value={category} onChange={(value) => value && setCategory(value)} data={[{ value: "all", label: "All categories" }, ...filterCategories.map((item) => ({ value: item.id, label: item.label }))]} searchable allowDeselect={false} /><DatePickerInput label="From" value={from || null} onChange={(value) => setFrom(value ?? "")} clearable valueFormat="MMM D, YYYY" firstDayOfWeek={0} /><DatePickerInput label="To" value={to || null} onChange={(value) => setTo(value ?? "")} clearable valueFormat="MMM D, YYYY" firstDayOfWeek={0} /><NumberInput label="Min amount" aria-label={`Minimum amount in ${currency}`} leftSection={<span className="currency-prefix">{currency}</span>} leftSectionWidth={52} value={min} onChange={(value) => setMin(String(value))} min={0} thousandSeparator="," decimalScale={2} /><NumberInput label="Max amount" aria-label={`Maximum amount in ${currency}`} leftSection={<span className="currency-prefix">{currency}</span>} leftSectionWidth={52} value={max} onChange={(value) => setMax(String(value))} min={0} thousandSeparator="," decimalScale={2} /><Select label="Payment mode" value={paymentMode} onChange={(value) => value && setPaymentMode(value as PaymentMode | "all")} data={[{ value: "all", label: "All payment modes" }, { value: "cash", label: "Cash" }, { value: "cheque", label: "Cheque" }, { value: "online", label: "Online payment" }]} allowDeselect={false} /><button className="text-button clear-filter-button" onClick={resetFilters}>Clear all</button></section>}
    <section className="ledger-list"><div className="ledger-list-heading"><span>{sorted.length} {sorted.length === 1 ? "entry" : "entries"}</span><span>Newest first</span></div>{sorted.map((transaction) => <TransactionRow key={transaction.id} transaction={transaction} currency={currency} customCategories={customCategories} onEdit={onEdit} onDelete={(item) => void remove(item)} deletePending={deletingId === transaction.id} />)}{!sorted.length && <EmptyState title="No matching entries" message="Try a different filter, or add a new transaction." action={<button className="primary-button small" onClick={onAdd}><Plus size={17} />Add transaction</button>} />}</section>
    {preview && <div className="modal-backdrop"><section className="import-dialog" role="dialog" aria-modal="true" aria-labelledby="import-title" aria-busy={importing}><header><div><span className="eyebrow">CSV import</span><h2 id="import-title">Review before importing</h2></div><button className="icon-button" disabled={importing} onClick={() => setPreview(null)} aria-label="Close"><X size={20} /></button></header>{importErrors.length > 0 && <div className="import-errors"><strong>{importErrors.length} rows need attention</strong>{importErrors.slice(0, 5).map((error) => <span key={error}>{error}</span>)}</div>}<div className="import-preview">{preview.slice(0, 8).map((row, index) => <div key={`${row.occurredOn}-${index}`}><span>{row.occurredOn}</span><strong>{row.note || getCategory(row.category, customCategories).label}</strong><span>{row.kind}</span><span>{row.amount} {currency}</span></div>)}</div><p>{preview.length} valid rows ready. Invalid rows will not be imported.</p><div className="dialog-actions"><button className="secondary-button" disabled={importing} onClick={() => setPreview(null)}>Cancel</button><button className="primary-button" disabled={!preview.length || importing} onClick={() => void importRows()}>{importing ? <><ButtonSpinner />Importing…</> : <><DownloadSimple size={17} />Import {preview.length} rows</>}</button></div></section></div>}
  </div>;
}
